### ISSUE TITLE
doesn't work with Go 1.4

### ISSUE THREAD

**Issue by lei-cao** [martinkirsche/wired-logic#1]
`./wired-logic.go:46: gifImage.Disposal undefined (type *gif.GIF has no field or method Disposal)`

Disposal is added in 1.5 

`The image/gif package includes a couple of generalizations. A multiple-frame GIF file can now have an overall bounds different from all the contained single frames' bounds. Also, the GIF struct now has a Disposal field that specifies the disposal method for each frame.`

**Comment by seletskiy** [comment]
@lei-cao: What the point of using outdated software?

**Comment by lei-cao** [comment]
hey you are right. Just create a log for it.
