### ISSUE TITLE
it's better to mark license type

### ISSUE THREAD

**Issue by wizicer** [martinkirsche/wired-logic#2]
As majored in electronic, the implementation really attracts me. It would be great to mark license and reference.

**Comment by martinkirsche** [comment]
Can you explain to me what you mean by "to mark license and reference"?

**Comment by wizicer** [comment]
There are 2 points:
- If you can assign a license type like **MIT/BSD license** to the project, this may encourage others who try to contribute to this project.
- As I'm interested in this idea which draw circuit in plain still image, I just want to have some **keywords/links** if this idea wasn't original proposed by this project.

**Comment by martinkirsche** [comment]
I added the MIT license two days ago.

I came up with the idea myself. However it was inspired by Wireworld (https://en.wikipedia.org/wiki/Wireworld) and Minecraft's Redstone. My first prototype even was a cellular automaton like Wireworld running as a shader within the GPU where each pixel charged its neighbours. But it was slow and I had to put a lot of repeaters everywhere.

**Comment by wizicer** [comment]
Thanks for your explanation, you really bring me a brand new world -- cellular automata.
